# Generated by Django 4.2 on 2023-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paymentStatus',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
