# Generated by Django 4.2 on 2023-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectDate', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=255)),
                ('logout', models.CharField(max_length=255)),
                ('selectWorkout', models.CharField(max_length=255)),
                ('trainedBy', models.CharField(max_length=255)),
            ],
        ),
    ]
