# Generated by Django 4.2 on 2023-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
